# .shed.yml supporting automatic pushes.
owner: portiahollyoak
name: twobit_to_fasta
description: Convert file from twobit to fasta format
long_description: |
  This tool converts a twobit formatted file and converts it to fasta format.
categories:
  - Convert Formats
homepage_url: http://artbio.fr
remote_repository_url: https://github.com/portiahollyoak/Tools
