# .shed.yml supporting automatic pushes.
owner: portiahollyoak
name: breakdancer
description: Breakdancer provides genome-wide detection of structural variation.
long_description: |
  BreakDancer (previously BreakDancerMax) provides genome-wide detection of five types of structural variants: insertions, deletions, inversions, inter- and intra-chromosomal translocations from next-generation short paired-end sequencing reads using read pairs that are mapped with unexpected separation distances or orientation.

categories:
  - Sequence Analysis
homepage_url: http://artbio.fr
remote_repository_url: https://github.com/portiahollyoak/Tools
