# .shed.yml supporting automatic pushes.
owner: portiahollyoak
name: pindel
description: Pindel detects genome-wide structural variation.
long_description: |
  Pindel can detect breakpoints of large deletions, medium sized insertions, inversions, tandem duplications and other structural variants at single-based resolution from next-gen sequence data. It uses a pattern growth approach to identify the breakpoints of these variants from paired-end short reads.

categories:
  - Sequence Analysis
homepage_url: http://artbio.fr
remote_repository_url: https://github.com/portiahollyoak/Tools
